name: prism
description: "A Flutter Social Media Project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  #! preferences feature
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  cupertino_icons: ^1.0.8

  #! clean architecture
  flutter_bloc: ^9.1.0
  bloc_concurrency: ^0.3.0
  equatable: ^2.0.7
  get_it: ^8.0.3
  dartz: ^0.10.1

  #! preferences feature
  flex_color_scheme: ^8.2.0
  shared_preferences: ^2.5.3
  #! auth feature
  http: ^1.4.0
  google_sign_in: ^6.3.0
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.4
  pinput: ^5.0.1
  flutter_svg: ^2.1.0
  #! account feature
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  path: ^1.9.1
  photo_manager: ^3.7.1
  video_player: ^2.10.0
  better_player_plus: ^1.0.8
  permission_handler: ^12.0.0+1

  #! live_stream feature
  socket_io_client: ^3.1.2
  fijkplayer_plus: ^0.0.1
  camera: ^0.11.0
  ffmpeg_kit_flutter_new: ^3.1.0
  record: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  injectable_generator: ^2.7.0
  build_runner: ^2.4.15

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/walk_through/
    - assets/images/auth/
    - assets/images/other/
    - .env
