dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.3.3
  get_it: ^7.6.4
  injectable: ^2.1.0
  freezed: ^2.4.5
  cached_network_image: ^3.3.0
  cloud_firestore: ^3.4.0
  internet_connection_checker: ^0.0.9+4
  firebase_core: ^1.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  injectable_generator: ^2.1.1
  freezed_annotation: ^2.4.1

